name: 提取電視台名稱

on:
  schedule:
    - cron: '15 */6 * * *'   # 每6小时运行一次
  workflow_dispatch:          # 支持手动触发

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download XML files
        run: |
          curl -L -o twepg.xml https://raw.githubusercontent.com/zzq1234567890/epg/main/twepg.xml
          curl -L -o swepg.xml https://raw.githubusercontent.com/zzq1234567890/epg/main/swepg.xml

      - name: Extract channel names (保持顺序)
        run: |
          python <<'EOF'
          import xml.etree.ElementTree as ET

          def extract_names(xml_file, output_file):
              try:
                  tree = ET.parse(xml_file)
                  root = tree.getroot()
                  seen = set()
                  channels = []
                  for c in root.findall('channel'):
                      name = c.get('display-name') or c.findtext('display-name') or c.get('id', '')
                      if name and name.strip() and name not in seen:
                          seen.add(name)
                          channels.append(name.strip())

                  with open(output_file, 'w', encoding='utf-8') as f:
                      f.write('\n'.join(channels))
                  print(f"✅ {xml_file}: 共提取 {len(channels)} 个频道，已保存到 {output_file}")
              except Exception as e:
                  print(f"❌ 解析 {xml_file} 出错: {e}")

          extract_names('twepg.xml', '繁體電視台目錄.txt')
          extract_names('swepg.xml', '简体电视台目录.txt')
          EOF

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "繁體電視台目錄.txt" "简体电视台目录.txt"
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update channel name lists"
            git push
          fi
