name: Extract Channel Names

on:
  schedule:
    - cron: '15 */6 * * *'   # 每6小时运行一次
  workflow_dispatch:          # 支持手动触发

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download XML files
        run: |
          curl -L -o twepg.xml https://raw.githubusercontent.com/zzq1234567890/epg/main/twepg.xml
          curl -L -o swepg.xml https://raw.githubusercontent.com/zzq1234567890/epg/main/swepg.xml

      - name: Extract channel names
        run: |
          python <<'EOF'
          import xml.etree.ElementTree as ET

          def extract_names(xml_file, output_file):
              try:
                  tree = ET.parse(xml_file)
                  root = tree.getroot()
                  channels = [c.get('display-name') or c.findtext('display-name') or c.get('id', '') for c in root.findall('channel')]
                  channels = [ch.strip() for ch in channels if ch and ch.strip()]
                  with open(output_file, 'w', encoding='utf-8') as f:
                      f.write('\n'.join(set(channels)))
                  print(f"Saved {len(channels)} names to {output_file}")
              except Exception as e:
                  print(f"Error parsing {xml_file}: {e}")

          extract_names('twepg.xml', '繁體電視台目錄.txt')
          extract_names('swepg.xml', '简体电视台目录.txt')
          EOF

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add 繁體電視台目錄.txt 简体电视台目录.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update channel name lists"
            git push
          fi
